### PR TITLE
LOOP-1099: Promote AlertSoundPlayer to LoopKit

### PR DESCRIPTION
**Pull request by rickpasetto**
...that way, it can be used elsewhere (see https://github.com/tidepool-org/dexcom-icgm-loop-plugin/pull/77 for where) for playing alert sounds (for example, in UI for choosing the sound itself).

See also https://github.com/tidepool-org/LoopKit/pull/81

https://github.com/tidepool-org/LoopWorkspace/pull/77

### CODE REVIEW

**Review by nhamming — APPROVED** [review]
LGTM

**Review by ps2 — COMMENTED** [review]
What is driving this? The comment says to be "used elsewhere". Do we have an elsewhere use case yet? Any future changes to this class will incur a dev cost, as they'll generally require PRs to both Loop and LoopKit, so putting it into LoopKit should only be done with some justification.

**Comment by rickpasetto** [comment]
@ps2 ah sorry I thought I put the link to the Dexcom PR (so many steps for this).  The idea is that when you need to select a sound for an alert, you'd want to hear it first when you choose it (like many other sound choosers).  See https://github.com/tidepool-org/dexcom-icgm-loop-plugin/pull/77

**Review by nhamming — APPROVED** [review]
LGTM

**Pull request merged**
