### PR TITLE
LOOP-1936 Do not provide temp basal recommendations when Closed Loop mode is OFF

### PR DESCRIPTION
**Pull request by darinkrauss**
- https://tidepool.atlassian.net/browse/LOOP-1936
- https://tidepool.atlassian.net/browse/LOOP-2335

### CODE REVIEW

**Comment by darinkrauss** [comment]
LW PR: https://github.com/tidepool-org/LoopWorkspace/pull/344

**Review by rickpasetto — COMMENTED** [review]
The code looks okay to me, but I'm afraid I'm going to have to defer to @ps2 on the correctness here...

**Review by nhamming — APPROVED** [review]
I'm not sure about this feature, but it is clearly defined in the ticket. One non-blocking question: will this be accepted by DIY?

LGTM

**Comment by darinkrauss** [comment]
@nhamming Yes, I pinged @ps2 in Slack about the likelihood DIY would accept it (or whether I needed to put it behind a feature flag) and he said go ahead without feature flag.

**Review by ps2 — APPROVED** [review]
LGTM!

**Pull request merged**
