### PR TITLE
[LOOP-4836] when rotating, re-calculate axis

### PR DESCRIPTION
**Pull request by nhamming**
https://tidepool.atlassian.net/browse/LOOP-4836

### CODE REVIEW

**Review by ps2 — COMMENTED** [review]
Is `viewWillTransition(to size: CGSize...` not being called when rotating? This looks like it will add additional redundant redraws.

**Comment by nhamming** [comment]
> Is `viewWillTransition(to size: CGSize...` not being called when rotating? This looks like it will add additional redundant redraws.

@ps2 Yes, it is being called, but the charts are not being redrawn with that call. Feel free to take a look

**Comment by ps2** [comment]
I think maybe the overridden viewWillTransition is missing a `await reloadData(animated: true)` call?  I believe all the redraw calls are supposed to go through reloadData() to coalesce all the things added to `refreshContext`

**Review by ps2 — CHANGES_REQUESTED** [review]
I'm trusting that this works; I'm just wondering if we should be following the existing pattern of setting the refresh context and then triggering a `reloadData` call.

The `viewWillTransition(to size...` is already setting the refresh context, but it's not triggering the reload data, which I think it should.

Rotating is really more about resizing than changing trait collections. So I think the reload probably belongs in the resize.

**Pull request closed without merging**
