### PR TITLE
Include mock cgm manager in release builds for now.

### PR DESCRIPTION
**Pull request by ps2**

### CODE REVIEW

**Comment by rickpasetto** [comment]
@ps2 is this because folks installing it via TestFlight need the mock CGM manager in place?

**Comment by ps2** [comment]
Yes; I think eventually we'll make a couple variants available via testflight, but for now, the mock devices really help with testing and design review.

**Comment by rickpasetto** [comment]
Just thinking aloud here: Would it make sense to have separate apps (bundle-ids) for the purpose of testing/design review?  Or is that too heavyweight?

**Review by rickpasetto — APPROVED** [review]
Sure, LGTM :)

**Review by nhamming — COMMENTED** [review]
LGTM

**Pull request merged**
