### PR TITLE
[LOOP-3021] allow deleting the cgm manager in the debug menu

### PR DESCRIPTION
**Pull request by nhamming**
https://tidepool.atlassian.net/browse/LOOP-3021

### CODE REVIEW

**Review by darinkrauss — APPROVED** [review]
LGTM! ⛵

**Comment by darinkrauss** [comment]
Actually, will this potentially leave the current CGM manager in an unstable state? That is, typically the delete action is triggered by the CGM manager itself and gives the CGM manager the ability to do cleanup (with the SDK or device) and then notify the delegate that it is ready for deletion. This just suddenly deletes the CGM manager.

**Comment by nhamming** [comment]
> Actually, will this potentially leave the current CGM manager in an unstable state? That is, typically the delete action is triggered by the CGM manager itself and gives the CGM manager the ability to do cleanup (with the SDK or device) and then notify the delegate that it is ready for deletion. This just suddenly deletes the CGM manager.

For the MockCGMManager and the DexcomCGMManager, no. The DexcomCGMManager should close communications, but that will timeout within 30 secs and not cause an issue. 

But I hear what you are getting at and will investigate.

**Comment by nhamming** [comment]
@darinkrauss updated to let the CGM manager handle deletion.

**Review by rickpasetto — APPROVED** [review]
See my comment in other PR, but other than that LGTM.

**Review by darinkrauss — APPROVED** [review]
LGTM, but requires approval of https://github.com/tidepool-org/LoopKit/pull/345 from @ps2 first.

**Comment by nhamming** [comment]
> LGTM, but requires approval of [tidepool-org/LoopKit#345](https://github.com/tidepool-org/LoopKit/pull/345) from @ps2 first.

agreed to make a ticket and discussion with Pete when he is available.

**Pull request merged**
