### PR TITLE
[LOOP-4884] when loop opens and loop status icon is animated, stop animating

### PR DESCRIPTION
**Pull request by nhamming**
https://tidepool.atlassian.net/browse/LOOP-4884

### CODE REVIEW

**Comment by nhamming** [comment]
@ps2 I'm curious about setting `loopInProgress = true` when the `loopStateView.open == true`. Should this be allowed?

**Comment by ps2** [comment]
If we start a loop when loop is in open mode, then there is a bug. So yes, this state should be considered invalid

**Review by ps2 — APPROVED** [review]
LGTM, but wondering how we could get into a state where loop was open and the animation was triggered.

**Comment by nhamming** [comment]
@ps2 I added that additional condition. 

The issue QA is seeing is that if the icon is pulsing continuously (likely another bug) and they turn automated dosing off, the icon is still closed and pulsing.

**Pull request merged**
