### PR TITLE
Fix crashing bug and Core Data managed object context issues

### PR DESCRIPTION
**Pull request by darinkrauss**
- https://tidepool.atlassian.net/browse/LOOP-2167
- Wrap usage of NSManagedObjectContext extension with perform or performAndWait
- Remove erroneous directory with malformed name

### CODE REVIEW

**Comment by darinkrauss** [comment]
LW PR: https://github.com/tidepool-org/LoopWorkspace/pull/334

**Review by nhamming — APPROVED** [review]
LGTM

**Review by ps2 — APPROVED** [review]
LGTM!

**Review by rickpasetto — COMMENTED** [review]
Why did you have to remove some Arabic localizations for this?  Is that intentional?

**Comment by darinkrauss** [comment]
@rickpasetto Yes, removing those two Arabic files is necessary to fix the bogus directory problem. Those are extra files in a bogus, extra directory (the directory name includes non-printable characters). The correct Arabic translation is still included in the correct directory.

**Comment by rickpasetto** [comment]
@darinkrauss cool, thanks for confirming!  Just was wondering if it was unintentional.  👍

**Review by rickpasetto — APPROVED** [review]

**Pull request merged**
