### PR TITLE
[LOOP-3112] Onboarding therapy setting uses pump supported increments

### PR DESCRIPTION
**Pull request by darinkrauss**
- https://tidepool.atlassian.net/browse/LOOP-3112
- Add support for CGM and pump manager images during onboarding
- Add support for pump manager supported increments during onboarding

### CODE REVIEW

**Review by nhamming — APPROVED** [review]
LGTM

**Comment by darinkrauss** [comment]
LW PR for build: https://github.com/tidepool-org/LoopWorkspace/pull/533

**Review by rickpasetto — APPROVED** [review]
LGTM

**Review by ps2 — COMMENTED** [review]
LGTM!

**Review by ps2 — APPROVED** [review]

**Pull request merged**
