### PR TITLE
Nate/fix/LOOP-309/bolus entry

### PR DESCRIPTION
**Pull request by nhamming**
https://tidepool.atlassian.net/browse/LOOP-309

correcting the colour used on the bolus entry view.

### CODE REVIEW

**Review by rickpasetto — APPROVED** [review]
LGTM 🧀

**Review by novalegra — APPROVED** [review]
👍

**Review by ps2 — APPROVED** [review]
LGTM!

**Review by darinkrauss — APPROVED** [review]
LGTM! 🤖

**Pull request merged**
