### PR TITLE
LOOP-1769: Turn off the debug menu unless DEBUG or running in iOS simulator

### PR DESCRIPTION
**Pull request by rickpasetto**
See [LOOP-1769](https://tidepool.atlassian.net/browse/LOOP-1769)

### CODE REVIEW

**Review by darinkrauss — CHANGES_REQUESTED** [review]
How are we going to get a DEBUG build to QA?

**Comment by rickpasetto** [comment]
@darinkrauss I asked this question in the bug.  Shawn [answered](https://tidepool.atlassian.net/browse/LOOP-1769?focusedCommentId=28739) that they haven't been using Scenarios since we moved to TestFlight.

**Comment by darinkrauss** [comment]
@rickpasetto Is this something we *need* to do *now*? What is the impetus for this change?

**Comment by rickpasetto** [comment]
@darinkrauss This ticket is now in the next sprint. Is it ok to merge this now?

**Review by darinkrauss — APPROVED** [review]
Approving for whenever we are ready to merge.

**Pull request closed without merging**
