### PR TITLE
LOOP-1417 Capture carbohydrate entries

### PR DESCRIPTION
**Pull request by darinkrauss**
- https://tidepool.atlassian.net/browse/LOOP-1417
- Remove DeletedCarbEntry from RemoteDataService and simulated core data

### CODE REVIEW

**Comment by darinkrauss** [comment]
Related LoopWorkspace PR: https://github.com/tidepool-org/LoopWorkspace/pull/176

**Review by rickpasetto — APPROVED** [review]
LGTM 🌡️

**Review by novalegra — APPROVED** [review]
👍

**Review by ps2 — APPROVED** [review]
LGTM!

**Comment by darinkrauss** [comment]
Deprecated by upcoming PR due to entirely new implementation based upon PR feedback.

**Pull request closed without merging**
