### PR TITLE
LOOP-1964: change LoopSettings.glucoseTargetRangeScheduleApplyingOverrideIfActive to glucoseTargetRangeConsideringOverrides(consideringPotentialCarbEntry ...?)

### PR DESCRIPTION
**Pull request by rickpasetto**
Instead of having the callers (WatchDataManager and BolusEntryViewModel) have to have the policy of dealing with a potential carb entry (which should ignore preMealOverride), move the logic to the source: where we actually ask for the glucoseTargetRange with applicable overrides.  This meant passing in any potential carb entry (hence changing it from a var to a func), but the usages were not many.  Note this effectively reverts the prior fix (https://github.com/tidepool-org/Loop/pull/269).

[LOOP-1964](https://tidepool.atlassian.net/browse/LOOP-1964)

LW PR: https://github.com/tidepool-org/LoopWorkspace/pull/285

### CODE REVIEW

**Review by ps2 — APPROVED** [review]
LGTM, I think this approach is the right one. Thanks. Only nit is having a function name with "Maybe" in it really begs the question of what the predicate is. Something like `glucoseTargetRangeScheduleMaybeApplyingOverride(consideringPotentialCarbEntry:` -> `effectiveGlucoseTargetRangeSchedule(consideringPotentialCarbEntry:` makes both the override application clear via the "effective" part, and the predication on potential carbs via the "consideringPotentialCarbEntry" argument.

**Comment by rickpasetto** [comment]
@ps2 I like it.  In fact, I like `effectiveGlucoseTargetRangeSchedule` more than `glucoseTargetRangeScheduleApplyingOverrideIfActive` so I'll rename that too

**Review by ps2 — CHANGES_REQUESTED** [review]
LGTM!

**Review by ps2 — APPROVED** [review]
Oops. Github seemed to remember the status from my last PR review; meant to approve.

**Pull request merged**
