### PR TITLE
LOOP-2458 Fix slow status bar update

### PR DESCRIPTION
**Pull request by darinkrauss**
- https://tidepool.atlassian.net/browse/LOOP-2458
- Add modificationCounter indices to prevent slow data access
- Move dosing decision data decoding from data access queue into utility queue

### CODE REVIEW

**Comment by darinkrauss** [comment]
Build LW PR: https://github.com/tidepool-org/LoopWorkspace/pull/411

**Comment by darinkrauss** [comment]
Build LW PR: https://github.com/tidepool-org/LoopWorkspace/pull/411

**Review by nhamming — APPROVED** [review]
LGTM

**Review by ps2 — APPROVED** [review]
LGTM!

**Pull request merged**
