### PR TITLE
nate/feature/LOOP-1293/display-mock-cgm-status-progress

### PR DESCRIPTION
**Pull request by nhamming**
https://tidepool.atlassian.net/browse/LOOP-1293

Displaying the cgm status progress

### CODE REVIEW

**Review by darinkrauss — APPROVED** [review]
LGTM! 🦁

**Review by ps2 — APPROVED** [review]
LGTM!

**Comment by nhamming** [comment]
Updates include requested changes from design review.

**Review by darinkrauss — APPROVED** [review]
LGTM! 🎧

**Review by ps2 — APPROVED** [review]
LGTM!

**Pull request merged**
